name: Docker Build & Push

on:
  pull_request:
    branches:
      - desarrollo
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t lucasaudisio/hola-mundaso:${{ github.sha }} .
      
    - name: Log in to Docker Hub
      run: docker login -u lucasaudisio -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image
      run: docker push lucasaudisio/hola-mundaso:${{ github.sha }}
